package JsonIntegration.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"JsonIntegration.structure.JsonArray", "JsonIntegration.structure.JsonFalse", "JsonIntegration.structure.JsonFile", "JsonIntegration.structure.JsonInteger", "JsonIntegration.structure.JsonNull", "JsonIntegration.structure.JsonObject", "JsonIntegration.structure.JsonProperty", "JsonIntegration.structure.JsonRealNumber", "JsonIntegration.structure.JsonString", "JsonIntegration.structure.JsonTrue", "JsonIntegration.structure.ParsingError", "JsonIntegration.structure.TextFile"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 2:
        return new JsonFile_BehaviorDescriptor();
      case 10:
        return new ParsingError_BehaviorDescriptor();
      case 0:
        return new JsonArray_BehaviorDescriptor();
      case 7:
        return new JsonRealNumber_BehaviorDescriptor();
      case 8:
        return new JsonString_BehaviorDescriptor();
      case 5:
        return new JsonObject_BehaviorDescriptor();
      case 6:
        return new JsonProperty_BehaviorDescriptor();
      case 4:
        return new JsonNull_BehaviorDescriptor();
      case 3:
        return new JsonInteger_BehaviorDescriptor();
      case 9:
        return new JsonTrue_BehaviorDescriptor();
      case 1:
        return new JsonFalse_BehaviorDescriptor();
      case 11:
        return new TextFile_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
