package JsonIntegration.behavior;

/*Generated by MPS */


public class JsonInteger_BehaviorDescriptor extends JsonElement_BehaviorDescriptor {
  public JsonInteger_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JsonIntegration.structure.JsonInteger";
  }
}
