package JsonIntegration.behavior;

/*Generated by MPS */


public class JsonTrue_BehaviorDescriptor extends JsonBoolean_BehaviorDescriptor {
  public JsonTrue_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JsonIntegration.structure.JsonTrue";
  }
}
