package JsonIntegration.behavior;

/*Generated by MPS */


public class JsonRealNumber_BehaviorDescriptor extends JsonElement_BehaviorDescriptor {
  public JsonRealNumber_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JsonIntegration.structure.JsonRealNumber";
  }
}
