package JsonIntegration.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class JsonElement_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public JsonElement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JsonIntegration.structure.JsonElement";
  }
}
