package JsonIntegration.behavior;

/*Generated by MPS */


public class JsonFalse_BehaviorDescriptor extends JsonBoolean_BehaviorDescriptor {
  public JsonFalse_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JsonIntegration.structure.JsonFalse";
  }
}
