package JsonIntegration.behavior;

/*Generated by MPS */


public abstract class JsonBoolean_BehaviorDescriptor extends JsonElement_BehaviorDescriptor {
  public JsonBoolean_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JsonIntegration.structure.JsonBoolean";
  }
}
