package JsonIntegration.behavior;

/*Generated by MPS */


public class JsonArray_BehaviorDescriptor extends JsonElement_BehaviorDescriptor {
  public JsonArray_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JsonIntegration.structure.JsonArray";
  }
}
