package JsonIntegration.behavior;

/*Generated by MPS */


public class JsonString_BehaviorDescriptor extends JsonElement_BehaviorDescriptor {
  public JsonString_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JsonIntegration.structure.JsonString";
  }
}
