package JsonIntegration.behavior;

/*Generated by MPS */


public class JsonObject_BehaviorDescriptor extends JsonElement_BehaviorDescriptor {
  public JsonObject_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JsonIntegration.structure.JsonObject";
  }
}
