package JsonIntegration.behavior;

/*Generated by MPS */


public class ParsingError_BehaviorDescriptor extends JsonElement_BehaviorDescriptor {
  public ParsingError_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "JsonIntegration.structure.ParsingError";
  }
}
