package JsonIntegration.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class JsonIntegration_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("9b93af94-3022-4b9e-8c13-685d6ad401ef(JsonIntegration)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
