package JsonIntegration.stubs;

/*Generated by MPS */

import jetbrains.mps.smodel.SModelReference;
import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.SModelFqName;
import jetbrains.mps.smodel.SModelId;

public class JsonPersistenceUtil {
  public static String STEREOTYPE = "json";

  public JsonPersistenceUtil() {
  }

  public static SModelReference refByModule(ModuleReference module) {
    String longName = "json";
    System.out.println("the model fqName is: " + module.getModuleFqName());
    return new SModelReference(new SModelFqName(longName, STEREOTYPE), SModelId.foreign(module.getModuleId().toString() + ":json"));
  }
}
